language: node_js

sudo: required

node_js:
- 10.14.0

services:
- docker

before_script:
- echo "Before Executed"
- chmod 755 ./*.sh
- ./installDockerCompose.sh
- /usr/local/bin/docker-compose up -d
- docker ps
- docker cp shell-in-container:/app/shell ./
- ls ./
- ls ./shell

install:
- echo "Install"

script: true
#  - go test ./cmd/bluepay-report-server/

after_success:
- ./travisDockerBuild.sh

notifications:
  slack: ibm-cio:Ll6gcxWaILLndlIMbaRpfclx
